# Generated by Django 2.2.5 on 2019-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('skill', '0001_initial'),
        ('profile', '0002_auto_20190213_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='language.Language'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='skill.Skill'),
        ),
    ]
