# Generated by Django 2.1.5 on 2019-01-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='languages',
            field=models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
