# Generated by Django 2.1.5 on 2019-01-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20190119_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='languages',
            field=models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English')], max_length=2, null=True),
        ),
    ]
