# Generated by Django 2.1.5 on 2019-01-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20190119_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='languages',
            field=models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English')], max_length=4, null=True),
        ),
    ]
