# Generated by Django 2.1.5 on 2019-02-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_auto_20190119_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='languages',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default=1, max_length=250, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='position_sector',
            field=models.CharField(default=1, max_length=200, verbose_name='Sector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True, default=12, verbose_name='Company URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=150, verbose_name='Position'),
        ),
    ]
