# Generated by Django 2.2.5 on 2019-10-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_description'),
        ('experience', '0006_auto_20190209_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='name',
        ),
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experience_company', to='company.Company'),
            preserve_default=False,
        ),
    ]
