# Generated by Django 2.2.5 on 2019-10-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_auto_20191002_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='industry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_industry', to='job.Industry'),
        ),
    ]
