# Generated by Django 2.2.5 on 2019-10-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_auto_20191002_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=250, verbose_name='Location'),
        ),
    ]
