# Generated by Django 2.2.5 on 2019-10-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0010_auto_20191002_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Company URL'),
        ),
    ]
