# Generated by Django 2.2.5 on 2019-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0011_auto_20191002_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
