# Generated by Django 2.1.5 on 2019-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school_url',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=250, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=250, verbose_name='School Name'),
        ),
    ]
