# Generated by Django 2.1.5 on 2019-01-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20190119_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
