# Generated by Django 2.1.5 on 2019-02-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_education_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='fieldOfStudy',
        ),
        migrations.RemoveField(
            model_name='education',
            name='location',
        ),
        migrations.AddField(
            model_name='education',
            name='chapter',
            field=models.CharField(default=1, max_length=250, verbose_name='Chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default=1, max_length=250, verbose_name='Degree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='link',
            field=models.URLField(blank=True, verbose_name='School URL'),
        ),
    ]
