# Generated by Django 2.2.5 on 2019-09-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20190209_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_current',
        ),
    ]
