# Generated by Django 2.2.5 on 2019-10-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_education_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='University Name')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='education_university', to='education.University'),
            preserve_default=False,
        ),
    ]
