# Generated by Django 2.2.5 on 2019-10-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20191002_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_university', to='education.University'),
        ),
    ]
