# Generated by Django 2.2.5 on 2019-10-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20191002_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Grade'),
            preserve_default=False,
        ),
    ]
