# Generated by Django 2.2.5 on 2019-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20191002_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='chapter',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, default=1, max_length=250, verbose_name='Degree'),
            preserve_default=False,
        ),
    ]
